# Initial state of the FSM

initial_state: "NORMAL_JOYSTICK_CONTROL"


events: # Maps from subscribing topic to signal ids
  joystick_override_on:
    topic: "joy_mapper_node/joystick_override"
    msg_type: "BoolStamped"
    trigger: True
  joystick_override_off:
    topic: "joy_mapper_node/joystick_override"
    msg_type: "BoolStamped"
    trigger: False
  obstacle_detected:
    topic: "tof_obstacle_detection_node/obstacle_detected"
    msg_type: "BoolStamped"
    trigger: True
  obstacle_cleared:
    topic: "tof_obstacle_detection_node/obstacle_cleared"
    msg_type: "BoolStamped"
    trigger: True

# Define nodes
nodes:
  anti_instagram: "anti_instagram_node/switch"
  line_detector_node: "line_detector_node/switch"
  lane_filter_node: "lane_filter_node/switch"
  ground_projection_node: "ground_projection_node/switch"
  lane_controller_node: "lane_controller_node/switch"
  led_emitter_node: "led_emitter_node/switch"
  tof_obstacle_detection_node: "tof_obstacle_detection_node/switch"
  # extras added


# Define state transitions

global_transitions:
  joystick_override_on: "NORMAL_JOYSTICK_CONTROL"
  joystick_override_off: "LANE_FOLLOWING"



states:
  NORMAL_JOYSTICK_CONTROL:
    active_nodes:
      - anti_instagram
      - lane_filter_node
      - line_detector_node
      - ground_projection_node
      - led_emitter_node
    lights: "GREEN"
  LANE_FOLLOWING:
    transitions:
      obstacle_detected: "STOP"
    active_nodes:
      - anti_instagram
      - line_detector_node
      - lane_filter_node
      - ground_projection_node
      - lane_controller_node
      - led_emitter_node
      - tof_obstacle_detection_node
    lights: "CAR_DRIVING"
  STOP:
    transitions:
      obstacle_cleared: "LANE_FOLLOWING"
    active_nodes:
      - anti_instagram
      - lane_filter_node
      - line_detector_node
      - ground_projection_node
      - led_emitter_node
      - tof_obstacle_detection_node
    lights: "JOYFULL"


